# Generated by Django 5.2.17 on 2026-08-13 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_total_rental_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id'], 'verbose_name': 'كتاب', 'verbose_name_plural': 'الكتب'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='المؤلف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='lms_app.category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الصفحات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='صورة المؤلف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='غلاف الكتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rental_peroid',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدة الإعارة بالأيام'),
        ),
        migrations.AlterField(
            model_name='book',
            name='retal_price_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='سعر الإعارة اليومي'),
        ),
        migrations.AlterField(
            model_name='book',
            name='statas',
            field=models.CharField(blank=True, choices=[('avalable', 'متاح'), ('rental', 'مُعار'), ('sold', 'مباع')], db_index=True, max_length=50, null=True, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=120, verbose_name='عنوان الكتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='إجمالي الإعارة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='اسم التصنيف'),
        ),
    ]
