# Generated by Django 5.2.17 on 2026-08-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='سنة الصدور'),
        ),
    ]
