# Generated by Django 5.2.17 on 2026-08-14 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_book_publication_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='مرجع الطلب')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('delivery_address', models.TextField(max_length=500, verbose_name='عنوان التسليم')),
                ('payment_method', models.CharField(choices=[('mock_card', 'بطاقة تجريبية'), ('mock_wallet', 'محفظة تجريبية')], max_length=20, verbose_name='طريقة الدفع')),
                ('payment_status', models.CharField(default='simulated_paid', max_length=20, verbose_name='حالة الدفع')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=120, verbose_name='عنوان الكتاب')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='سعر الوحدة')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='lms_app.book', verbose_name='الكتاب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lms_app.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
    ]
